In [1]:
import numpy as np

## Iterating Arrays
##### Iterating means going through elements one by one.
##### As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
##### If we iterate on a 1-D array it will go through each element one by one.

In [2]:
arr = np.array([1,2,4,5])

for x in arr:
    print(x)

1
2
4
5


### 2D & 3D iteration 

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [4]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### Iterating Arrays Using nditer()
##### The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration.
##### Iterating on Each Scalar Element
##### In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.



In [6]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
