In [1]:
import numpy as np


## Unknown Dimension
##### You are allowed to have one "unknown" dimension.
##### Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
##### Pass -1 as the value, and NumPy will calculate this number for you.

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,-1)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Flattening the arrays
##### Flattening array means converting a multidimensional array into a 1D array.
##### We can use reshape(-1) to do this.

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
