In [1]:
import numpy as np

## Copy and View
#####  copies owns the data, and views does not own the data
##### Every NumPy array has the attribute base that returns None if the array owns the data.

In [2]:
arr = np.array([1,2,3,4])
x = arr.copy()
arr[1] = 99

print(arr)
print(x)


[ 1 99  3  4]
[1 2 3 4]


In [3]:
arr = np.array([1,2,3,4,5,6])
y = arr.view()
arr[0] = -121

print(arr)
print(y)

[-121    2    3    4    5    6]
[-121    2    3    4    5    6]


In [4]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
