In [1]:
import numpy as np

## Shape
##### The shape of an array is the number of elements in each dimension.

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [3]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## Reshaping arrays
##### Reshaping means changing the shape of an array.
##### The shape of an array is the number of elements in each dimension.
##### By reshaping we can add or remove dimensions or change number of elements in each dimension.

#### From 1D to 2D

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
newarr2 = arr.reshape(3,4)

print(newarr)
print()
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### From 1D to 3D


In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
